// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSnkTsOtnVCGk9hVSsJffjjPnTn1v1z60',
    appId: '1:645023011886:web:1eff283627f6c11c417bbf',
    messagingSenderId: '645023011886',
    projectId: 'projects-80c27',
    authDomain: 'projects-80c27.firebaseapp.com',
    storageBucket: 'projects-80c27.firebasestorage.app',
    measurementId: 'G-BMQTSGJJ6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt6jbX2Q7J5Yl-WLgS9R2446Pj69tfC1Q',
    appId: '1:645023011886:android:f37d5f8e9a3658d8417bbf',
    messagingSenderId: '645023011886',
    projectId: 'projects-80c27',
    storageBucket: 'projects-80c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6iLeVDl9ja8kwqd2zfzkUrdKx7HlMUDg',
    appId: '1:645023011886:ios:2ac1aa62dda84aaf417bbf',
    messagingSenderId: '645023011886',
    projectId: 'projects-80c27',
    storageBucket: 'projects-80c27.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6iLeVDl9ja8kwqd2zfzkUrdKx7HlMUDg',
    appId: '1:645023011886:ios:2ac1aa62dda84aaf417bbf',
    messagingSenderId: '645023011886',
    projectId: 'projects-80c27',
    storageBucket: 'projects-80c27.firebasestorage.app',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSnkTsOtnVCGk9hVSsJffjjPnTn1v1z60',
    appId: '1:645023011886:web:acf00604103d3273417bbf',
    messagingSenderId: '645023011886',
    projectId: 'projects-80c27',
    authDomain: 'projects-80c27.firebaseapp.com',
    storageBucket: 'projects-80c27.firebasestorage.app',
    measurementId: 'G-H7V3015RSL',
  );
}
